<?php

declare(strict_types=1);

return [
    'id' => 'reports',
    'name' => 'Reports',
    'version' => '0.1.0',
    'enabled' => true,
    'requires' => [],
    'requires_modules' => ['notifications'],
    'routes' => __DIR__ . '/routes.php',
    'admin' => [
        'menu' => [
            [
                'label' => 'Reports',
                'route' => 'admin/complaints-reports.php',
                'permission' => 'reports.view',
            ],
        ],
    ],
    'permissions' => [
        [
            'key' => 'reports.view',
            'label' => 'Reports View',
            'description' => 'View topic reports and user complaints.',
            'group' => 'reports',
            'default' => false,
        ],
        [
            'key' => 'reports.manage',
            'label' => 'Reports Manage',
            'description' => 'Moderate topic reports and user complaints.',
            'group' => 'reports',
            'default' => false,
        ],
        [
            'key' => 'reports.create',
            'label' => 'Reports Create',
            'description' => 'Create topic reports and user complaints.',
            'group' => 'reports',
            'default' => true,
        ],
    ],
    'config' => [
        'topic_report_reasons_json' => [
            'label' => 'Konu Rapor Nedenleri',
            'type' => 'text',
            'default' => '',
            'section' => 'reports',
            'tooltip' => 'Public konu raporlama penceresinde gösterilecek nedenleri belirler.',
        ],
        'api_reports_rate_limit' => [
            'label' => 'Konu Şikayet Listeleme Limiti',
            'type' => 'number',
            'default' => '10',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1000,
            'tooltip' => 'Belirlenen süre içinde konu şikayetlerini listeleme veya okuma için en fazla kaç istek yapılabileceğini belirler.',
        ],
        'api_reports_rate_window' => [
            'label' => 'Konu Şikayet Listeleme Süresi (dakika)',
            'type' => 'number',
            'default' => '1',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1440,
            'tooltip' => 'Konu şikayet listeleme limitinin kaç dakikalık süre içinde uygulanacağını belirler.',
        ],
        'api_report_submit_rate_limit' => [
            'label' => 'Konu Şikayet Gönderim Limiti',
            'type' => 'number',
            'default' => '5',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1000,
            'tooltip' => 'Belirlenen süre içinde bir oturumun en fazla kaç konu şikayeti gönderebileceğini belirler.',
        ],
        'api_report_submit_rate_window' => [
            'label' => 'Konu Şikayet Gönderim Süresi (dakika)',
            'type' => 'number',
            'default' => '10',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1440,
            'tooltip' => 'Konu şikayet gönderim limitinin kaç dakikalık süre içinde uygulanacağını belirler.',
        ],
        'api_user_reports_rate_limit' => [
            'label' => 'Kullanıcı Şikayet Listeleme Limiti',
            'type' => 'number',
            'default' => '10',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1000,
            'tooltip' => 'Belirlenen süre içinde kullanıcı şikayetlerini listeleme veya okuma için en fazla kaç istek yapılabileceğini belirler.',
        ],
        'api_user_reports_rate_window' => [
            'label' => 'Kullanıcı Şikayet Listeleme Süresi (dakika)',
            'type' => 'number',
            'default' => '1',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1440,
            'tooltip' => 'Kullanıcı şikayet listeleme limitinin kaç dakikalık süre içinde uygulanacağını belirler.',
        ],
        'api_user_report_submit_rate_limit' => [
            'label' => 'Kullanıcı Şikayet Gönderim Limiti',
            'type' => 'number',
            'default' => '5',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1000,
            'tooltip' => 'Belirlenen süre içinde bir oturumun en fazla kaç kullanıcı şikayeti gönderebileceğini belirler.',
        ],
        'api_user_report_submit_rate_window' => [
            'label' => 'Kullanıcı Şikayet Gönderim Süresi (dakika)',
            'type' => 'number',
            'default' => '10',
            'section' => 'rate_limit',
            'min' => 1,
            'max' => 1440,
            'tooltip' => 'Kullanıcı şikayet gönderim limitinin kaç dakikalık süre içinde uygulanacağını belirler.',
        ],
    ],
    'events' => [],
    'lifecycle' => \App\Modules\Reports\Services\ReportsLifecycle::class,
    'migrations' => __DIR__ . '/Database/migrations',
    'lang' => __DIR__ . '/lang',
];
