<?php

declare(strict_types=1);

return [
    'id' => 'leaderboard',
    'name' => 'Leaderboard',
    'version' => '0.1.0',
    'enabled' => true,
    'requires' => [],
    'requires_modules' => [],
    'routes' => __DIR__ . '/routes.php',
    'admin' => [],
    'permissions' => [
        [
            'key' => 'leaderboard.admin',
            'label' => 'Leaderboard Admin',
            'description' => 'Manage leaderboard settings, cache, and recalculation controls.',
            'group' => 'leaderboard',
            'default' => false,
        ],
    ],
    'config' => [
        'leaderboard_enabled' => [
            'label' => 'Liderlik Sistemi Aktif',
            'type' => 'bool',
            'default' => '1',
            'section' => 'leaderboard',
            'tooltip' => 'Public liderlik tablosu sayfasını ve liderlik widgetlarını açar veya kapatır.',
        ],
        'leaderboard_disabled_message' => [
            'label' => 'Sistem Kapalı Mesajı',
            'type' => 'textarea',
            'default' => 'Liderlik tablosu şu anda kapalı. Lütfen daha sonra tekrar kontrol edin.',
            'section' => 'leaderboard',
            'tooltip' => 'Liderlik sistemi kapalıyken public sayfada kullanıcılara gösterilecek mesaj.',
        ],
        'leaderboard_cache_ttl_daily' => [
            'label' => 'Günlük Önbellek Süresi (saniye)',
            'type' => 'number',
            'default' => '900',
            'section' => 'leaderboard',
            'tooltip' => 'Günlük liderlik tablosu önbelleğinin kaç saniye geçerli kalacağını belirler.',
        ],
        'leaderboard_cache_ttl_weekly' => [
            'label' => 'Haftalık Önbellek Süresi (saniye)',
            'type' => 'number',
            'default' => '3600',
            'section' => 'leaderboard',
            'tooltip' => 'Haftalık liderlik tablosu önbelleğinin kaç saniye geçerli kalacağını belirler.',
        ],
        'leaderboard_cache_ttl_monthly' => [
            'label' => 'Aylık Önbellek Süresi (saniye)',
            'type' => 'number',
            'default' => '21600',
            'section' => 'leaderboard',
            'tooltip' => 'Aylık liderlik tablosu önbelleğinin kaç saniye geçerli kalacağını belirler.',
        ],
        'leaderboard_cache_ttl_quarterly' => [
            'label' => 'Üç Aylık Önbellek Süresi (saniye)',
            'type' => 'number',
            'default' => '43200',
            'section' => 'leaderboard',
            'tooltip' => 'Üç aylık liderlik tablosu önbelleğinin kaç saniye geçerli kalacağını belirler.',
        ],
        'leaderboard_cache_ttl_yearly' => [
            'label' => 'Yıllık Önbellek Süresi (saniye)',
            'type' => 'number',
            'default' => '86400',
            'section' => 'leaderboard',
            'tooltip' => 'Yıllık liderlik tablosu önbelleğinin kaç saniye geçerli kalacağını belirler.',
        ],
        'leaderboard_cache_ttl_all_time' => [
            'label' => 'Tüm Zamanlar Önbellek Süresi (saniye)',
            'type' => 'number',
            'default' => '86400',
            'section' => 'leaderboard',
            'tooltip' => 'Tüm zamanlar liderlik tablosu önbelleğinin kaç saniye geçerli kalacağını belirler.',
        ],
        'leaderboard_exclude_admins' => [
            'label' => 'Adminleri Hariç Tut',
            'type' => 'bool',
            'default' => '1',
            'section' => 'leaderboard',
            'tooltip' => 'Admin yetkisine sahip kullanıcıları liderlik sıralamasından çıkarır.',
        ],
        'leaderboard_show_sidebar' => [
            'label' => 'Ana Sayfa Yan Panelinde Göster',
            'type' => 'bool',
            'default' => '1',
            'section' => 'leaderboard',
            'tooltip' => 'Ana sayfa yan panelindeki liderlik widgetını gösterir veya gizler.',
        ],
        'leaderboard_sidebar_limit' => [
            'label' => 'Yan Panel Kullanıcı Limiti',
            'type' => 'number',
            'default' => '5',
            'section' => 'leaderboard',
            'tooltip' => 'Yan panel liderlik widgetında gösterilecek en fazla kullanıcı sayısı.',
        ],
        'leaderboard_show_profile' => [
            'label' => 'Profil Sayfasında Göster',
            'type' => 'bool',
            'default' => '1',
            'section' => 'leaderboard',
            'tooltip' => 'Kullanıcı profilinde liderlik özeti widgetını gösterir veya gizler.',
        ],
        'leaderboard_profile_limit' => [
            'label' => 'Profil Widget Limiti',
            'type' => 'number',
            'default' => '10',
            'section' => 'leaderboard',
            'tooltip' => 'Profil liderlik widgetında gösterilecek en fazla kategori veya satır sayısı.',
        ],
        'leaderboard_exclude_banned' => [
            'label' => 'Yasaklı Kullanıcıları Hariç Tut',
            'type' => 'bool',
            'default' => '1',
            'section' => 'leaderboard',
            'tooltip' => 'Yasaklı kullanıcıları liderlik sıralamasından çıkarır.',
        ],
    ],
    'events' => [
        'topic.published' => [
            \App\Modules\Leaderboard\Services\LeaderboardCacheInvalidator::class,
        ],
    ],
    'lifecycle' => \App\Modules\Leaderboard\Services\LeaderboardLifecycle::class,
    'migrations' => __DIR__ . '/Database/migrations',
    'lang' => __DIR__ . '/lang',
];
