<?php

declare(strict_types=1);

return [
    'id' => 'notifications',
    'name' => 'Notifications',
    'version' => '0.1.0',
    'enabled' => true,
    'requires' => [],
    'requires_modules' => [],
    'routes' => __DIR__ . '/routes.php',
    'admin' => [
        'menu' => [
            [
                'label' => 'Notifications',
                'route' => 'admin/notifications.php',
                'permission' => 'notifications.view',
            ],
        ],
    ],
    'permissions' => [
        [
            'key' => 'notifications.view',
            'label' => 'Notifications View',
            'description' => 'View notification history, templates, logs, and user notification center data.',
            'group' => 'notifications',
            'default' => false,
        ],
        [
            'key' => 'notifications.manage',
            'label' => 'Notifications Manage',
            'description' => 'Manage notification settings, templates, retention, and manual sends.',
            'group' => 'notifications',
            'default' => false,
        ],
        [
            'key' => 'notifications.dispatch',
            'label' => 'Notifications Dispatch',
            'description' => 'Create notifications from system, moderation, and module events.',
            'group' => 'notifications',
            'default' => false,
        ],
    ],
    'config' => [
        'notif_center_enabled' => [
            'label' => 'Notification Center Enabled',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Disable new sends and mute user header notification payloads.',
        ],
        'notif_allow_global_broadcasts' => [
            'label' => 'Allow Global Broadcasts',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Allow manual notifications without a target user id.',
        ],
        'notif_allow_direct_messages' => [
            'label' => 'Allow Direct Messages',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Allow manual notifications for a specific target user id.',
        ],
        'notif_respect_user_preferences' => [
            'label' => 'Respect User Preferences',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Filter notification views by user preference settings.',
        ],
        'notif_require_https_links' => [
            'label' => 'Require HTTPS External Links',
            'type' => 'bool',
            'default' => '0',
            'tooltip' => 'Reject external manual notification links unless they use HTTPS.',
        ],
        'notif_show_header_badge' => [
            'label' => 'Show Header Badge',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Show unread notification counts in the public header.',
        ],
        'notif_auto_mark_link_click' => [
            'label' => 'Auto Mark Link Click',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Mark notifications read when their link is opened.',
        ],
        'notif_enable_read_more' => [
            'label' => 'Enable Read More',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Collapse long user notification messages behind a read-more control.',
        ],
        'notif_empty_state_tips' => [
            'label' => 'Show Empty State Tips',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Show explanatory empty-state copy on notification pages.',
        ],
        'notif_dropdown_limit' => [
            'label' => 'Header Dropdown Limit',
            'type' => 'number',
            'default' => '5',
            'min' => 1,
            'max' => 20,
            'tooltip' => 'Maximum notifications shown in the header dropdown.',
        ],
        'notif_user_page_per_page' => [
            'label' => 'User Page Per Page',
            'type' => 'number',
            'default' => '10',
            'min' => 5,
            'max' => 50,
            'tooltip' => 'Notifications shown per page in the user notification center.',
        ],
        'notif_user_message_lines' => [
            'label' => 'User Message Lines',
            'type' => 'number',
            'default' => '3',
            'min' => 1,
            'max' => 8,
            'tooltip' => 'Visible line count before long notification messages collapse.',
        ],
        'notif_default_type' => [
            'label' => 'Default Notification Type',
            'type' => 'select',
            'default' => 'info',
            'options' => [
                'info' => 'Info',
                'success' => 'Success',
                'warning' => 'Warning',
                'error' => 'Error',
                'system' => 'System',
            ],
            'tooltip' => 'Default type selected in the manual notification composer.',
        ],
        'notif_default_link' => [
            'label' => 'Default Link',
            'type' => 'text',
            'default' => '',
            'tooltip' => 'Fallback link used when the manual composer link is empty.',
        ],
        'notif_max_title_length' => [
            'label' => 'Max Title Length',
            'type' => 'number',
            'default' => '120',
            'min' => 20,
            'max' => 255,
            'tooltip' => 'Maximum manual notification title length.',
        ],
        'notif_max_message_length' => [
            'label' => 'Max Message Length',
            'type' => 'number',
            'default' => '800',
            'min' => 80,
            'max' => 5000,
            'tooltip' => 'Maximum manual notification message length.',
        ],
        'notif_history_per_page' => [
            'label' => 'History Per Page',
            'type' => 'number',
            'default' => '20',
            'min' => 10,
            'max' => 100,
            'tooltip' => 'Rows shown per page in admin notification history.',
        ],
        'notif_history_message_preview' => [
            'label' => 'History Message Preview',
            'type' => 'number',
            'default' => '140',
            'min' => 40,
            'max' => 500,
            'tooltip' => 'Maximum message preview length in admin history tables.',
        ],
        'notif_retention_days' => [
            'label' => 'Retention Days',
            'type' => 'number',
            'default' => '30',
            'min' => 0,
            'max' => 3650,
            'tooltip' => 'Delete notifications older than this many days when settings are saved; 0 disables cleanup.',
        ],
        'notif_events_enabled' => [
            'label' => 'Event Notifications Enabled',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Allow automatic notifications from comments, mentions, reports, and moderation events.',
        ],
        'notif_event_comments_enabled' => [
            'label' => 'Comment Event Notifications',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Enable comment and reply notification events.',
        ],
        'notif_event_mentions_enabled' => [
            'label' => 'Mention Event Notifications',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Enable @mention notification events.',
        ],
        'notif_event_topic_moderation_enabled' => [
            'label' => 'Topic Moderation Notifications',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Enable topic approved, rejected, and revision-requested notifications.',
        ],
        'notif_event_favorites_enabled' => [
            'label' => 'Favorite Topic Notifications',
            'type' => 'bool',
            'default' => '0',
            'tooltip' => 'Enable notifications when favorite topics receive new comments.',
        ],
        'notif_event_skip_actor' => [
            'label' => 'Skip Actor Notifications',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Avoid notifying users about their own action.',
        ],
        'notif_event_dedupe_enabled' => [
            'label' => 'Dedupe Event Notifications',
            'type' => 'bool',
            'default' => '1',
            'tooltip' => 'Prevent duplicate notifications for the same recipient and entity event.',
        ],
        'notif_email_channel_ready' => [
            'label' => 'Email Queue Enabled',
            'type' => 'bool',
            'default' => '0',
            'tooltip' => 'Queue email rows for email-enabled notification templates.',
        ],
        'notif_email_queue_max_attempts' => [
            'label' => 'Email Queue Max Attempts',
            'type' => 'number',
            'default' => '3',
            'min' => 1,
            'max' => 10,
            'tooltip' => 'Maximum worker attempts for queued notification email.',
        ],
        'notif_system_sender' => [
            'label' => 'System Sender Name',
            'type' => 'text',
            'default' => 'Sistem',
            'tooltip' => 'Sender label used for automated system notifications.',
        ],
        'notif_welcome_enabled' => [
            'label' => 'Welcome Notification Enabled',
            'type' => 'bool',
            'default' => '0',
            'tooltip' => 'Send a welcome notification to newly registered users.',
        ],
        'notif_welcome_msg' => [
            'label' => 'Welcome Message',
            'type' => 'textarea',
            'default' => 'Aramiza hos geldiniz! Kurallari okumayi unutmayin.',
            'tooltip' => 'Message body used for new-user welcome notifications.',
        ],
    ],
    'events' => [
        'comment.created' => [
            \App\Modules\Notifications\Listeners\NotificationEventSubscriber::class,
        ],
        'topic.published' => [
            \App\Modules\Notifications\Listeners\NotificationEventSubscriber::class,
        ],
        'report.created' => [
            \App\Modules\Notifications\Listeners\NotificationEventSubscriber::class,
        ],
    ],
    'lifecycle' => \App\Modules\Notifications\Services\NotificationsLifecycle::class,
    'migrations' => __DIR__ . '/Database/migrations',
    'lang' => __DIR__ . '/lang',
];
