<?php

declare(strict_types=1);

return [
    'id' => 'notifications',
    'name' => 'Notifications',
    'version' => '0.1.0',
    'enabled' => true,
    'requires' => [],
    'requires_modules' => [],
    'routes' => __DIR__ . '/routes.php',
    'admin' => [
        'menu' => [
            [
                'label' => 'Notifications',
                'route' => 'admin/notifications.php',
                'permission' => 'notifications.view',
            ],
        ],
    ],
    'permissions' => [
        [
            'key' => 'notifications.view',
            'label' => 'Notifications View',
            'description' => 'View notification history, templates, logs, and user notification center data.',
            'group' => 'notifications',
            'default' => false,
        ],
        [
            'key' => 'notifications.manage',
            'label' => 'Notifications Manage',
            'description' => 'Manage notification settings, templates, retention, and manual sends.',
            'group' => 'notifications',
            'default' => false,
        ],
        [
            'key' => 'notifications.dispatch',
            'label' => 'Notifications Dispatch',
            'description' => 'Create notifications from system, moderation, and module events.',
            'group' => 'notifications',
            'default' => false,
        ],
    ],
    'config' => [
        'notif_center_enabled' => [
            'label' => 'Bildirim Merkezi Aktif',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Kapatılırsa kullanıcı bildirim API çıktısı sessize alınır ve yeni bildirim gönderimi durdurulur.',
        ],
        'notif_allow_global_broadcasts' => [
            'label' => 'Genel Yayınlara İzin Ver',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Kapatılırsa hedef kullanıcı seçilmeden tüm kullanıcılara bildirim gönderilemez.',
        ],
        'notif_allow_direct_messages' => [
            'label' => 'Kullanıcıya Özel Bildirimlere İzin Ver',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Kapatılırsa belirli kullanıcı ID hedefli bildirim gönderilemez.',
        ],
        'notif_respect_user_preferences' => [
            'label' => 'Kullanıcı Tercihlerini Uygula',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Kullanıcıların kapattığı bildirim tipleri kullanıcı sayfası ve üst menü bildirim API çıktısında gizlenir.',
        ],
        'notif_require_https_links' => [
            'label' => 'Harici Linklerde HTTPS Zorunlu',
            'type' => 'bool',
            'default' => '0',
            'section' => 'notifications',
            'tooltip' => 'Açıksa dış bağlantılı manuel bildirimlerde HTTPS zorunlu olur.',
        ],
        'notif_show_header_badge' => [
            'label' => 'Üst Menü Rozetini Göster',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Kapatılırsa okunmamış sayı rozeti gizlenir, ancak bildirim menüsü görüntülenebilir.',
        ],
        'notif_auto_mark_link_click' => [
            'label' => 'Linke Tıklayınca Okundu Yap',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Bildirim linki açıldığında bildirim otomatik okundu olarak işaretlenir.',
        ],
        'notif_enable_read_more' => [
            'label' => 'Uzun Mesajlarda Genişletme Butonu',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Uzun kullanıcı bildirimlerini genişletme butonunun arkasında kısaltır.',
        ],
        'notif_empty_state_tips' => [
            'label' => 'Boş Durum Yardım Metni Göster',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Bildirim sayfalarında açıklayıcı boş durum metinlerini gösterir.',
        ],
        'notif_dropdown_limit' => [
            'label' => 'Üst Menü Bildirim Limiti',
            'type' => 'number',
            'default' => '5',
            'section' => 'notifications',
            'min' => 1,
            'max' => 20,
            'tooltip' => 'Üst menü açılır bildirim listesinde gösterilecek maksimum bildirim sayısı.',
        ],
        'notif_user_page_per_page' => [
            'label' => 'Kullanıcı Sayfası Sayfa Başına',
            'type' => 'number',
            'default' => '10',
            'section' => 'notifications',
            'min' => 5,
            'max' => 50,
            'tooltip' => 'Kullanıcı bildirim merkezinde sayfa başına gösterilecek bildirim sayısı.',
        ],
        'notif_user_message_lines' => [
            'label' => 'Kullanıcı Mesaj Satır Limiti',
            'type' => 'number',
            'default' => '3',
            'section' => 'notifications',
            'min' => 1,
            'max' => 8,
            'tooltip' => 'Uzun bildirim mesajları kısaltılmadan önce gösterilecek satır sayısı.',
        ],
        'notif_default_type' => [
            'label' => 'Varsayılan Bildirim Tipi',
            'type' => 'select',
            'default' => 'info',
            'section' => 'notifications',
            'options' => [
                'info' => 'Bilgi',
                'success' => 'Başarılı',
                'warning' => 'Uyarı',
                'error' => 'Hata',
                'system' => 'Sistem',
            ],
            'tooltip' => 'Manuel bildirim oluşturucuda varsayılan seçilecek bildirim tipi.',
        ],
        'notif_default_link' => [
            'label' => 'Varsayılan Bildirim Linki',
            'type' => 'string',
            'default' => '',
            'section' => 'notifications',
            'tooltip' => 'Manuel bildirimde link alanı boşsa kullanılacak varsayılan bağlantı.',
        ],
        'notif_max_title_length' => [
            'label' => 'Maksimum Başlık Uzunluğu',
            'type' => 'number',
            'default' => '120',
            'section' => 'notifications',
            'min' => 20,
            'max' => 255,
            'tooltip' => 'Manuel bildirim başlığının maksimum karakter uzunluğu.',
        ],
        'notif_max_message_length' => [
            'label' => 'Maksimum Mesaj Uzunluğu',
            'type' => 'number',
            'default' => '800',
            'section' => 'notifications',
            'min' => 80,
            'max' => 5000,
            'tooltip' => 'Manuel bildirim mesajının maksimum karakter uzunluğu.',
        ],
        'notif_history_per_page' => [
            'label' => 'Admin Geçmiş Sayfa Başına',
            'type' => 'number',
            'default' => '10',
            'section' => 'notifications',
            'min' => 5,
            'max' => 100,
            'tooltip' => 'Admin bildirim geçmişinde sayfa başına gösterilecek kayıt sayısı.',
        ],
        'notif_history_message_preview' => [
            'label' => 'Admin Geçmiş Mesaj Önizleme',
            'type' => 'number',
            'default' => '140',
            'section' => 'notifications',
            'min' => 40,
            'max' => 500,
            'tooltip' => 'Admin geçmiş tablolarında gösterilecek mesaj önizleme uzunluğu.',
        ],
        'notif_retention_days' => [
            'label' => 'Saklama Süresi Gün',
            'type' => 'number',
            'default' => '30',
            'section' => 'notifications',
            'min' => 0,
            'max' => 3650,
            'tooltip' => 'Ayarlar kaydedildiğinde bu günden eski bildirimler temizlenir; 0 temizliği kapatır.',
        ],
        'notif_events_enabled' => [
            'label' => 'Otomatik Olay Bildirimleri',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Yorum, bahsetme, rapor ve moderasyon olaylarından otomatik bildirim oluşturulmasına izin verir.',
        ],
        'notif_admin_registration_site_enabled' => [
            'label' => 'Yeni Kullanıcı Kaydı Admin Site İçi Bildirimi',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Yeni kullanıcı kayıt olduğunda admin ve yetkili hesaplara site içi bildirim gönderir.',
        ],
        'notif_admin_registration_email_enabled' => [
            'label' => 'Yeni Kullanıcı Kaydı Admin E-postası',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Yeni kullanıcı kayıt olduğunda admin ve yetkili hesaplara e-posta kuyruğu üzerinden bildirim gönderir.',
        ],
        'notif_event_comments_enabled' => [
            'label' => 'Yorum Olayları',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Yorum ve yanıt bildirim olaylarını etkinleştirir.',
        ],
        'notif_event_mentions_enabled' => [
            'label' => 'Bahsetme Olayları',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => '@bahsetme bildirim olaylarını etkinleştirir.',
        ],
        'notif_event_topic_moderation_enabled' => [
            'label' => 'Konu Moderasyon Olayları',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Konu onay, ret ve revizyon isteği bildirimlerini etkinleştirir.',
        ],
        'notif_event_favorites_enabled' => [
            'label' => 'Favori Konu Olayları',
            'type' => 'bool',
            'default' => '0',
            'section' => 'notifications',
            'tooltip' => 'Favori konulara yeni yorum geldiğinde bildirim oluşturur.',
        ],
        'notif_event_skip_actor' => [
            'label' => 'Kendi İşleminden Bildirim Alma',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Kullanıcıların kendi işlemleri için kendilerine bildirim gitmesini engeller.',
        ],
        'notif_event_dedupe_enabled' => [
            'label' => 'Tekrar Bildirimlerini Engelle',
            'type' => 'bool',
            'default' => '1',
            'section' => 'notifications',
            'tooltip' => 'Aynı alıcı ve aynı olay için tekrar bildirim oluşturulmasını engeller.',
        ],
        'notif_email_channel_ready' => [
            'label' => 'E-posta Kuyruğu Aktif',
            'type' => 'bool',
            'default' => '0',
            'section' => 'notifications',
            'tooltip' => 'E-posta açık bildirim metinlerinden kuyruk kaydı oluşturur; cron worker bu kayıtları SMTP/mail ayarlarıyla gönderir.',
        ],
        'notif_email_queue_max_attempts' => [
            'label' => 'E-posta Deneme Hakkı',
            'type' => 'number',
            'default' => '3',
            'section' => 'notifications',
            'min' => 1,
            'max' => 10,
            'tooltip' => 'Kuyruktaki bildirim e-postaları için maksimum worker deneme sayısı.',
        ],
        'notif_system_sender' => [
            'label' => 'Sistem Gönderen Adı',
            'type' => 'string',
            'default' => 'Sistem',
            'section' => 'notifications',
            'tooltip' => 'Otomatik sistem bildirimlerinde kullanılacak gönderen etiketi.',
        ],
        'notif_welcome_enabled' => [
            'label' => 'Site İçi Hoş Geldin Bildirimi',
            'type' => 'bool',
            'default' => '0',
            'section' => 'notifications',
            'tooltip' => 'Yeni kayıt olan kullanıcılara hoş geldin bildirimi gönderir.',
        ],
        'notif_welcome_msg' => [
            'label' => 'Site İçi Hoş Geldin Mesajı',
            'type' => 'text',
            'default' => 'Aramıza hoş geldiniz! Kuralları okumayı unutmayın.',
            'section' => 'notifications',
            'tooltip' => 'Yeni kullanıcı hoş geldin bildiriminin mesaj metni.',
        ],
    ],
    'events' => [
        'comment.created' => [
            \App\Modules\Notifications\Listeners\NotificationEventSubscriber::class,
        ],
        'topic.published' => [
            \App\Modules\Notifications\Listeners\NotificationEventSubscriber::class,
        ],
        'report.created' => [
            \App\Modules\Notifications\Listeners\NotificationEventSubscriber::class,
        ],
    ],
    'lifecycle' => \App\Modules\Notifications\Services\NotificationsLifecycle::class,
    'migrations' => __DIR__ . '/Database/migrations',
    'lang' => __DIR__ . '/lang',
];
