-- ============================================================================
-- AUTO-GENERATED MIGRATION STUB
-- ============================================================================
-- Generated by: scripts/guard/migration_autogen.php
-- Generated at: 2026-07-04T22:07:41+02:00
-- Scope: root
--
-- IMPORTANT: Review and adjust SQL before push/deploy.
-- This file is generated to keep migration discipline automatic.
-- ============================================================================

-- Detected DDL signals in diff (preview):
--   - $pdo->exec("ALTER TABLE message_thread_participants ADD COLUMN typing_at TEXT NULL");
--   - $pdo->exec("ALTER TABLE message_thread_participants ADD COLUMN typing_at TIMESTAMP NULL AFTER last_read_at");
--   - $pdo->exec("ALTER TABLE message_messages ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0 AFTER body");

-- Candidate SQL statements auto-detected from added lines:
$pdo->exec("ALTER TABLE message_thread_participants ADD COLUMN typing_at TEXT NULL");
$pdo->exec("ALTER TABLE message_thread_participants ADD COLUMN typing_at TIMESTAMP NULL AFTER last_read_at");
$pdo->exec("ALTER TABLE message_messages ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0 AFTER body");

